### ISSUE TITLE
ServerBuilderImpl does not work with https

### ISSUE THREAD

**Issue by dfreis** [niloc132/webbit-gwt#12]
Window.Location.getProtocol() (which returns js $wnd.location.protocol) returns 'https:', including the colon (:) but ServerBuilderImpl does not respect it within the constructor:

```
public ServerBuilderImpl() {
		urlBuilder.setProtocol("https".equals(Window.Location.getProtocol()) ? "wss": "ws").setHash(null);
	}
```

should be:
```
urlBuilder.setProtocol("https:".equals(Window.Location.getProtocol()) ? "wss": "ws").setHash(null);
```

**Comment by niloc132** [comment]
Whoops! I could have sworn I tested this. By the same token, I'm surprised that `wss` and `ws` doesn't _also_ need a `:` on them, but that's not how UrlBuilder works (it allows an optional `:`, `:/`, or `://`, and replaces them all with `://`).

**Comment by niloc132** [comment]
This should be generally working now.
